# Generated by Django 2.2.4 on 2019-09-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
                ('photo', models.ImageField(default='img/no-image.jpg', upload_to='author_photo/%Y/%m/%d/')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('date_of_dead', models.DateField(verbose_name='Дата смерти')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
                ('summary', models.CharField(max_length=1000, verbose_name='Описание')),
                ('cover', models.FileField(default='img/no-image.jpg', upload_to='book_cover/%Y/%m/%d/')),
                ('imprint', models.CharField(max_length=1000, verbose_name='Хуйпойми')),
                ('ISBN', models.CharField(max_length=100, verbose_name='ISBN')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Author', verbose_name='Автор')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Genre', verbose_name='Жанр')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(to='catalog.Book', verbose_name='Книги'),
        ),
    ]
