# Generated by Django 2.2.3 on 2019-10-06 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191005_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ISBN',
        ),
        migrations.RemoveField(
            model_name='book',
            name='imprint',
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique key for this particular key', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=100, verbose_name='Издательство')),
                ('ISBN', models.CharField(max_length=100, verbose_name='ISBN')),
                ('return_date', models.DateField(verbose_name='Дата возврата книги')),
                ('status', models.CharField(blank=True, choices=[('m', 'maintains'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book', verbose_name='Книга')),
            ],
            options={
                'ordering': ['return_date'],
            },
        ),
    ]
