# Generated by Django 2.2.3 on 2019-10-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191008_2122'),
        ('catalog', '0006_auto_20191008_1107'),
    ]

    operations = [
    ]
