# Generated by Django 2.2.3 on 2019-10-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191009_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='default', max_length=100),
        ),
    ]
